services:
  postgresdb:
    image: kartoza/postgis:16-3.4
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3
    container_name: psql-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orbis
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./init-db:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: orbis
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/orbis
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgresdb:
        condition: service_healthy

volumes:
  db_data:
